export type Pattern = {id:string;title:string;english:string;category:string;summary:string;problem:string;solution:string;caution:string;tags:string[];games:{name:string;note:string}[];related:string[];tone:string;diagram:number};
export const categories=['全部模式','核心机制','目标与挑战','探索与空间','系统与经济','社交与协作','反馈与体验'];
export const patterns:Pattern[]=[
{id:'001',title:'核心循环',english:'Core Loop',category:'核心机制',summary:'让行动、反馈与成长相互连接，形成玩家愿意再次投入的体验循环。',problem:'如何让单次操作产生延续的动机，而不是在完成后失去方向？',solution:'识别玩家最常重复的行动，给出可感知的结果，再让结果改变下一轮的选择。先验证一轮是否有趣，再加入长期成长；缩短操作与反馈之间的间隔。',caution:'重复本身不会产生乐趣。如果每次选择都没有变化，循环容易变成机械劳动。',tags:['循环设计','玩家动机'],games:[{name:'星露谷物语',note:'种植、收获与收入支持下一轮农场规划，季节变化又带来新的约束。'},{name:'怪物猎人',note:'狩猎获得素材，制作装备，再挑战新的怪物；准备和战斗彼此支撑。'}],related:['002','011'],tone:'green',diagram:0},
{id:'002',title:'风险与回报',english:'Risk–Reward Trade-off',category:'核心机制',summary:'把诱人的收益放在可判断的风险之后，让每次选择都值得权衡。',problem:'如何避免玩家始终采用同一种最安全的策略？',solution:'提供多个收益与风险不同的方案。用清晰线索帮助玩家估计代价，保留撤退或稳健推进的选择，让高风险方案的成功回报足够明确。',caution:'不可预知的惩罚会把风险判断变成猜测。避免让高风险选项同时拥有最低成本和最高收益。',tags:['决策设计','策略深度'],games:[{name:'黑暗之魂',note:'继续探索可能获取更多资源，也可能失去携带的灵魂；返回篝火构成另一种选择。'},{name:'杀戮尖塔',note:'选择精英战可能获得遗物，也会消耗生命，影响后续路线的生存空间。'}],related:['007','003'],tone:'orange',diagram:1},
{id:'003',title:'渐进式挑战',english:'Progressive Challenge',category:'目标与挑战',summary:'随着玩家能力增长，逐步引入更复杂的考验，让学习与挑战保持同步。',problem:'如何让新玩家有能力开始，同时让熟练玩家持续投入？',solution:'先在低压力情境中引入单一能力，再变化条件，最后组合已经学会的技能。将难度拆分为速度、信息量、精度和决策数量，逐项调整。',caution:'数值膨胀并不等于更深的挑战。突然叠加多个新要求，会让玩家难以理解失败原因。',tags:['难度曲线','学习体验'],games:[{name:'蔚蓝',note:'章节围绕移动能力逐步组合障碍，短距离重试支持技能练习。'}],related:['004','012'],tone:'blue',diagram:2},
{id:'004',title:'分层目标',english:'Layered Goals',category:'目标与挑战',summary:'把长远愿望拆成可执行的小目标，让玩家既知道眼前做什么，也知道为何而做。',problem:'长线进度过于遥远时，如何维持行动方向？',solution:'让即时目标、阶段目标和长期目标嵌套：一次行动推动一项任务，一项任务支持一个阶段成果。不同时间跨度的目标应相互解释，而不是争夺注意力。',caution:'目标过多会成为待办清单。突出当前最重要的方向，并允许玩家自行安排顺序。',tags:['目标设计','成长系统'],games:[{name:'星露谷物语',note:'日常照料作物、季节性收集与农场建设提供不同时间跨度的目标。'}],related:['001','003'],tone:'blue',diagram:2},
{id:'005',title:'好奇心驱动的探索',english:'Curiosity-driven Exploration',category:'探索与空间',summary:'用可见但尚未理解的线索吸引注意，让“我想知道”成为前进的理由。',problem:'没有任务箭头时，如何让玩家主动探索世界？',solution:'展示一个能被注意到的信息缺口，例如远处的结构、异常声音或未解释的现象。探索应带来能回应疑问的发现，并留下新的可追踪线索。',caution:'线索需要有可读性。反复用无意义的空洞奖励好奇心，会削弱玩家对环境的信任。',tags:['环境引导','内在动机'],games:[{name:'星际拓荒',note:'不同地点的知识互相指向，玩家通过理解线索形成自己的探索顺序。'}],related:['006','011'],tone:'teal',diagram:3},
{id:'006',title:'能力门槛与回访',english:'Ability Gating & Revisiting',category:'探索与空间',summary:'让暂时无法通过的空间留下记忆，在获得新能力后赋予旧地图新的意义。',problem:'如何让成长改变玩家与已有空间的关系？',solution:'先让玩家看见障碍和另一侧的可能性，再通过新能力改变可达区域。提供清晰的视觉标识或地图记忆，避免玩家只能依赖漫无目的的回溯。',caution:'回访应带来新路线或新理解。重复穿越没有变化的长路径容易消耗耐心。',tags:['关卡结构','能力成长'],games:[{name:'空洞骑士',note:'移动能力拓展可达路线，早期无法抵达的位置成为后续探索的目标。'}],related:['005','004'],tone:'teal',diagram:3},
{id:'007',title:'有限资源与取舍',english:'Resource Scarcity',category:'系统与经济',summary:'用有限的资源承载互相竞争的需求，让分配本身成为有意义的玩法。',problem:'当所有行动都可以轻易执行时，如何产生真正的策略？',solution:'选择少量重要资源，让多个有价值的行动竞争它们。说明恢复方式与消耗后果，并通过补给节奏调整玩家的规划跨度。',caution:'过度稀缺会鼓励囤积、拖延和反复读档。需要区分紧张感与无法行动的挫败。',tags:['资源管理','有意义的选择'],games:[{name:'生化危机 2',note:'弹药、治疗物品与背包空间让战斗、绕行和携带选择彼此关联。'}],related:['002','008'],tone:'purple',diagram:4},
{id:'008',title:'构筑协同',english:'Build Synergy',category:'系统与经济',summary:'让不同能力与道具相互放大，把单次选择积累成有个性的策略。',problem:'如何让多个独立奖励形成整体策略，而不是简单相加？',solution:'围绕少量可理解的触发条件设计协同，例如攻击次数、状态叠加或资源转换。让玩家能识别当前构筑缺少的部分，同时提供通用备选。',caution:'协同过强可能让未凑齐组合的选择失去价值。避免只有一种组合能够稳定通关。',tags:['构筑设计','系统交互'],games:[{name:'杀戮尖塔',note:'卡牌、遗物与能量分配相互影响，同一张牌在不同牌组中有不同价值。'}],related:['007','002'],tone:'purple',diagram:4},
{id:'009',title:'互补式协作',english:'Complementary Cooperation',category:'社交与协作',summary:'让玩家各有所长，又需要彼此配合，使合作成为体验的一部分。',problem:'如何让多人游玩产生合作，而不只是同时做各自的事情？',solution:'分配不同但同样重要的能力，设计需要交替或同时行动的目标。为共享信息与角色交换留出空间，并确保每位玩家都能感知自己的贡献。',caution:'不要把全部主动权集中给一人。强制依赖也可能放大能力差距和等待时间。',tags:['多人合作','角色分工'],games:[{name:'双人成行',note:'关卡中的互补能力要求两位玩家交替支持对方，合作方式随场景变化。'}],related:['010','002'],tone:'rose',diagram:5},
{id:'010',title:'共享目标',english:'Shared Objectives',category:'社交与协作',summary:'用共同的成败标准连接个人行动，让沟通与协调自然发生。',problem:'如何降低团队内部目标冲突，让玩家关注整体结果？',solution:'设置清晰的团队成果，并让不同角色能以多种方式贡献。反馈应呈现整体进度和关键支援行为，避免只奖励最显眼的个人表现。',caution:'只有共同分数还不够。如果个体贡献无法识别，玩家可能感到无力或依赖他人完成。',tags:['团队目标','沟通协作'],games:[{name:'胡闹厨房 2',note:'共享订单、时间和厨房空间，使备菜、烹饪与上菜必须协调。'}],related:['009','011'],tone:'rose',diagram:5},
{id:'011',title:'即时且清晰的反馈',english:'Immediate Feedback',category:'反馈与体验',summary:'让玩家看见行动的结果，理解系统的规则，并及时调整下一步。',problem:'如何让玩家判断自己的操作是否生效、为什么生效？',solution:'把视觉、声音和状态变化与实际结果对齐，区分成功、失败与未生效。优先呈现影响决策的信息，为不同感知需求提供替代通道。',caution:'更强烈不一定更清晰。过量特效和重复提示会掩盖真正重要的状态。',tags:['操作手感','信息可读性'],games:[{name:'哈迪斯',note:'攻击效果、受击反应和生命状态共同传达战斗中的行为结果。'}],related:['001','012'],tone:'green',diagram:0},
{id:'012',title:'低成本重试',english:'Low-cost Retry',category:'反馈与体验',summary:'缩短失败到再次行动的距离，让挫败转化为学习的下一次机会。',problem:'玩家愿意学习，但失败后的重复准备让他们放弃，怎么办？',solution:'让检查点接近正在练习的挑战，快速恢复控制。保留能解释失败的线索，减少无关的重复路程，同时让成功依然体现掌握。',caution:'如果失败几乎没有信息，快速重试也只会加速困惑。重试成本应与预期体验匹配。',tags:['失败设计','学习循环'],games:[{name:'蔚蓝',note:'快速重新开始当前小段关卡，让玩家把注意力留在具体移动技巧上。'}],related:['003','011'],tone:'green',diagram:0}
];
